"""Isolated retail-agent context plane for Nova Context Network.

This package is intentionally separate from institutional target-v2 review
context, accepted chronology, accepted-state synchronization, institutional
constraints, and institutional Reflex Memory.
"""

from .boundaries import assert_retail_module_allowed, validate_retail_package_imports
from .config import RetailContextConfig
from .context_delta import (
    build_context_delta,
    load_context_delta_schema,
    validate_context_delta,
)
from .schema import (
    SCHEMA_VERSION,
    load_retail_context_schema,
    retail_context_validator,
    validate_retail_context_object,
)
from .sources import (
    FixtureRetailSourceAdapter,
    RetailSourceAdapter,
    is_source_usable,
    load_source_observation_schema,
    load_source_registry_schema,
    validate_source_observation,
    validate_source_registry,
)
from .state_ping import build_state_ping
from .control_store import (
    PaymentClaimDecision,
    RateLimitDecision,
    RetailProductionControlStore,
    SQLiteRetailProductionControlStore,
)
from .production_config import (
    RetailProductionControlConfig,
    RetailProductionControlConfigError,
)
from .production_controls import (
    RetailProductionControlError,
    RetailResourceDeliveryOutcome,
    RetailServiceAdmissionOutcome,
    claim_settled_payment_for_delivery,
    delivery_outcome_allows_resource_delivery,
    evaluate_retail_control_readiness,
    evaluate_retail_pre_payment_admission,
    load_retail_production_control_schema,
    mark_retail_delivery_complete,
    mark_retail_delivery_failed,
    record_retail_operational_incident,
    service_admission_allows_payment_challenge,
    set_retail_service_mode,
    validate_retail_production_control_record,
)
from .proof_evidence import (
    load_retail_controlled_proof_schema,
    validate_retail_controlled_proof_evidence,
)
from .request_binding import (
    PreparedRetailRequest,
    canonical_json_bytes,
    prepare_context_delta_request,
    prepare_state_ping_request,
    retail_request_digest,
)
from .runtime_config import RetailRuntimeConfig, RetailRuntimeConfigError
from .runtime_delivery import (
    DeliveredRetailResource,
    RetailDeliveryRecoveryError,
    RetailRuntimeDeliveryCapability,
    claim_or_resume_retail_delivery,
    deliver_or_redeliver_retail_resource,
)
from .x402_payment import (
    ACCESS_EFFECT,
    AUTHORITY_EFFECT,
    PAYMENT_ASSET,
    PAYMENT_NETWORK,
    PAYMENT_SCHEME,
    PRICING_MODEL,
    RETAIL_PAYMENT_HEADER_NAMES,
    RETAIL_RESOURCE_PRICE_CATALOG,
    X402_VERSION,
    RetailPaymentChallenge,
    RetailPaymentOutcome,
    RetailX402Facilitator,
    RetailX402PaymentError,
    build_retail_payment_challenge,
    build_retail_payment_requirement,
    load_retail_x402_payment_schema,
    payment_outcome_allows_resource_access,
    payment_receipt_allows_resource_access,
    process_retail_x402_payment,
    run_retail_x402_payment_loop,
    validate_retail_payment_requirement,
    validate_retail_x402_payment_record,
)

__all__ = [
    "RetailContextConfig",
    "FixtureRetailSourceAdapter",
    "RetailSourceAdapter",
    "RetailPaymentChallenge",
    "RetailPaymentOutcome",
    "PaymentClaimDecision",
    "RateLimitDecision",
    "RetailProductionControlConfig",
    "RetailProductionControlConfigError",
    "RetailProductionControlError",
    "RetailProductionControlStore",
    "RetailRuntimeConfig",
    "RetailRuntimeConfigError",
    "RetailRuntimeDeliveryCapability",
    "RetailDeliveryRecoveryError",
    "DeliveredRetailResource",
    "PreparedRetailRequest",
    "RetailResourceDeliveryOutcome",
    "RetailServiceAdmissionOutcome",
    "SQLiteRetailProductionControlStore",
    "RetailX402Facilitator",
    "RetailX402PaymentError",
    "SCHEMA_VERSION",
    "ACCESS_EFFECT",
    "AUTHORITY_EFFECT",
    "PAYMENT_ASSET",
    "PAYMENT_NETWORK",
    "PAYMENT_SCHEME",
    "PRICING_MODEL",
    "RETAIL_PAYMENT_HEADER_NAMES",
    "RETAIL_RESOURCE_PRICE_CATALOG",
    "X402_VERSION",
    "assert_retail_module_allowed",
    "build_context_delta",
    "build_state_ping",
    "build_retail_payment_challenge",
    "build_retail_payment_requirement",
    "canonical_json_bytes",
    "claim_or_resume_retail_delivery",
    "claim_settled_payment_for_delivery",
    "delivery_outcome_allows_resource_delivery",
    "deliver_or_redeliver_retail_resource",
    "evaluate_retail_control_readiness",
    "evaluate_retail_pre_payment_admission",
    "is_source_usable",
    "load_retail_context_schema",
    "load_context_delta_schema",
    "load_source_observation_schema",
    "load_source_registry_schema",
    "load_retail_x402_payment_schema",
    "load_retail_production_control_schema",
    "load_retail_controlled_proof_schema",
    "mark_retail_delivery_complete",
    "mark_retail_delivery_failed",
    "payment_outcome_allows_resource_access",
    "payment_receipt_allows_resource_access",
    "process_retail_x402_payment",
    "prepare_context_delta_request",
    "prepare_state_ping_request",
    "record_retail_operational_incident",
    "retail_context_validator",
    "retail_request_digest",
    "service_admission_allows_payment_challenge",
    "set_retail_service_mode",
    "validate_retail_context_object",
    "validate_context_delta",
    "validate_retail_package_imports",
    "validate_retail_payment_requirement",
    "validate_retail_production_control_record",
    "validate_retail_controlled_proof_evidence",
    "validate_retail_x402_payment_record",
    "validate_source_observation",
    "validate_source_registry",
    "run_retail_x402_payment_loop",
]
